"""
Rule database for Claude/Anthropic API breaking changes.

This version was partly regenerated by actually reading Anthropic's live
release notes (fetched 2026-08-27) and extracting structured rules from the
raw changelog text — this is a manual stand-in for the step that should run
automatically via an LLM call in the real product (see extract_rules.py).

One correction from the first version: "sampling-params-rejected" was
originally attributed to specific *models* (Opus 4.7+/Sonnet 5). The actual
changelog entry (Python SDK v1.0, 2026-08-20) shows it's an *SDK-version*
change — v1.0 removes temperature/top_p/top_k from Messages methods
entirely, for any model. That's a meaningfully different (and more useful)
condition to check for. Left as a lesson: a hand-written rule can be subtly
wrong even when it "sounds right" — this is exactly why the real rule
database needs to come from the source text, not paraphrase.
"""

RULES = [
    {
        "id": "sdk-v1-sampling-params-removed",
        "pattern": r"(?<!#)\b(temperature|top_p|top_k)\s*=\s*[0-9.]+",
        "applies_if_model": None,  # SDK-version issue, not model-specific
        "severity": "HIGH",
        "deadline": "2026-08-20 (Python SDK v1.0)",
        "title": "temperature/top_p/top_k removed from Messages methods in Python SDK v1.0",
        "detail": (
            "Python SDK v1.0 (2026-08-20) removes temperature, top_p, and "
            "top_k from Messages methods entirely — for any model, not a "
            "specific one. Correction from an earlier version of this rule, "
            "which wrongly scoped it to Opus 4.7+/Sonnet 5 only."
        ),
        "fix": "Remove the parameter, or pin anthropic<1.0 until you've migrated (see the v1 migration guide).",
    },
    {
        "id": "sdk-v1-text-completions-removed",
        "pattern": r"client\.completions\.create|anthropic\.Completion",
        "applies_if_model": None,
        "severity": "HIGH",
        "deadline": "2026-08-20 (Python SDK v1.0)",
        "title": "Legacy Text Completions API removed in Python SDK v1.0",
        "detail": "The old Text Completions surface is gone in v1.0 of the Python SDK.",
        "fix": "Migrate to the Messages API (client.messages.create).",
    },
    {
        "id": "manual-thinking-budget",
        "pattern": r"thinking\s*=\s*\{\s*[\"']type[\"']\s*:\s*[\"']enabled[\"']\s*,\s*[\"']budget_tokens[\"']",
        "applies_if_model": ["opus-4-7", "opus-5", "sonnet-5"],
        "severity": "HIGH",
        "deadline": "already active",
        "title": "Manual thinking budget rejected — needs adaptive thinking",
        "detail": (
            "Manually specifying a fixed thinking token budget is being "
            "phased out in favor of adaptive thinking / effort levels."
        ),
        "fix": "Replace budget_tokens with an `effort` level (e.g. \"high\", \"xhigh\").",
    },
    {
        "id": "opus5-effort-xhigh-thinking-disabled",
        "pattern": r"effort\s*=\s*[\"'](xhigh|max)[\"']",
        "applies_if_model": ["opus-5"],
        "severity": "MEDIUM",
        "deadline": "2026-07-24 (Claude Opus 5 launch)",
        "title": "Disabling thinking at xhigh/max effort is rejected on Opus 5",
        "detail": (
            "Confirmed directly in the Opus 5 release notes (2026-07-24): "
            "thinking: {\"type\": \"disabled\"} with effort xhigh/max returns "
            "a 400 error. This is a documented behavior change from Opus 4.8."
        ),
        "fix": "Either drop the explicit thinking=disabled, or lower the effort level.",
    },
    {
        "id": "assistant-prefill-removed",
        "pattern": r"[\"']role[\"']\s*:\s*[\"']assistant[\"']\s*,\s*[\"']content[\"']\s*:\s*[\"'][^\"']*[\"']",
        "applies_if_model": ["opus-4-7", "opus-5", "sonnet-5"],
        "severity": "MEDIUM",
        "deadline": "already active",
        "title": "Assistant message prefill removed on recent models",
        "detail": "Pre-filling the start of the assistant's reply is no longer supported on newer models.",
        "fix": "Move the prefilled text into the system prompt or a formatting instruction instead.",
    },
    {
        "id": "experimental-endpoint-retiring",
        "pattern": r"/v1/experimental/(generate_prompt|improve_prompt|templatize_prompt)",
        "applies_if_model": None,
        "severity": "HIGH",
        "deadline": "2026-08-17 (already passed)",
        "title": "Experimental prompt endpoints retired",
        "detail": "generate_prompt / improve_prompt / templatize_prompt under /v1/experimental/ have been shut down.",
        "fix": "Migrate to the stable prompt-engineering workflow in the Console, or vendor the logic yourself.",
    },
    {
        "id": "model-deprecated-sonnet4-opus4",
        "pattern": r"claude-(sonnet|opus)-4-\d{8}",
        "applies_if_model": None,
        "severity": "HIGH",
        "deadline": "deprecated — migrate now",
        "title": "Pinned to a deprecated Claude 4 model snapshot",
        "detail": "Claude Sonnet 4 and Opus 4 are deprecated in favor of the 4.5/5 line.",
        "fix": "Update the model string to the current Sonnet/Opus 5 snapshot.",
    },
    {
        "id": "model-retired-opus-4-1",
        "pattern": r"claude-opus-4-1-20250805",
        "applies_if_model": None,
        "severity": "HIGH",
        "deadline": "2026-08-05 (already retired)",
        "title": "Claude Opus 4.1 fully retired — all requests now error",
        "detail": "Confirmed in the 2026-08-05 release notes: Opus 4.1 (claude-opus-4-1-20250805) is fully retired. Every request to it now returns an error, not a warning.",
        "fix": "Upgrade to Claude Opus 5.",
    },
    {
        "id": "fast-mode-removed-opus-4-7",
        "pattern": r"claude-opus-4-7[\s\S]{0,200}speed\s*[:=]\s*[\"']fast[\"']",
        "applies_if_model": None,
        "severity": "MEDIUM",
        "deadline": "2026-07-24 (Claude Opus 5 launch)",
        "title": "Fast mode removed for Claude Opus 4.7 — now errors instead of falling back",
        "detail": (
            "Requests to claude-opus-4-7 with speed: \"fast\" now return an "
            "error. Unlike Opus 4.6, they no longer silently fall back to "
            "standard speed."
        ),
        "fix": "Migrate to Claude Opus 5 or Opus 4.8 to keep using fast mode.",
    },
    {
        "id": "model-tentative-retirement-sonnet45",
        "pattern": r"claude-sonnet-4-5",
        "applies_if_model": None,
        "severity": "LOW",
        "deadline": "no retirement currently scheduled (confirmed 2026-08-27)",
        "title": "Claude Sonnet 4.5 — status check",
        "detail": "Verified directly against Anthropic's release notes: Sonnet 4.5 has no deprecation scheduled as of 2026-08-27. Downgraded from an earlier, unverified MEDIUM-severity guess.",
        "fix": "No action needed right now — just keep an eye on the release notes.",
    },
]

# --- Rules below this line came from running extract_rules.py for real ---
#
# On 2026-08-27, extract_rules.py was run against Anthropic's actual release
# notes (pipeline_runs/2026-08-27_changelog_input.txt) with a real API key.
# It found 14 breaking changes; 6 were the same ones already hand-written
# above (under different ids — the two extraction passes, one human, one
# automated, didn't converge on identical naming, which is itself worth
# noting rather than papering over). These 8 are the genuinely new ones the
# automated pass caught and hand-extraction had missed. Copied over as-is
# from pipeline_runs/2026-08-27_extracted_rules.json, spot-checked for
# sanity but not further hand-tuned — that's the point of this being
# automated. See ast_scan.py's GENERIC_RULE_EXCLUDE_IDS for which rules get
# bespoke AST logic vs. run through the generic node-scoped regex engine.
NEW_RULES = [
    {
        "id": "beta-files-skills-sdk-shape-change",
        "pattern": r"client\.beta\.(files|skills)\b",
        "applies_if_model": None,
        "severity": "HIGH",
        "deadline": "2026-08-27",
        "title": "client.beta.files and client.beta.skills no longer send beta headers and return new response shapes",
        "detail": "In Python SDK 1.2.0+, accessing files or skills through the beta namespace now behaves identically to the non-beta namespace — old beta headers/response shapes are gone. client.beta.skills.delete() now deletes a Skill together with all its versions, and BetaSkill is renamed BetaContainerSkill.",
        "fix": "Migrate to client.files and client.skills directly; update BetaSkill references to BetaContainerSkill.",
    },
    {
        "id": "python-sdk-v1-httpx-to-httpx2",
        "pattern": r"import\s+httpx(?!2)|from\s+httpx(?!2)\s+import|httpx\.(Client|AsyncClient|Timeout|Proxy|Limits|Transport)",
        "applies_if_model": None,
        "severity": "HIGH",
        "deadline": "2026-08-20 (Python SDK v1.0)",
        "title": "Python SDK v1.0 moves HTTP layer from httpx to httpx2",
        "detail": "Python SDK v1.0 replaces the httpx dependency with httpx2. Custom http_client/Timeout/transport objects built from httpx must be rebuilt from httpx2; code relying on libraries that monkeypatch httpx needs httpx2.alias_httpx() at startup.",
        "fix": "Replace `import httpx` with `import httpx2` for custom HTTP clients/transports, and call httpx2.alias_httpx() at startup if you use a library that monkeypatches httpx.",
    },
    {
        "id": "python-sdk-v1-compaction-control-removed",
        "pattern": r"compaction_control",
        "applies_if_model": None,
        "severity": "MEDIUM",
        "deadline": "2026-08-20 (Python SDK v1.0)",
        "title": "Python SDK v1.0 removes the tool runner's client-side compaction_control",
        "detail": "Python SDK v1.0 removes the compaction_control option from the client-side tool runner. Code passing this parameter will break after upgrading.",
        "fix": "Remove any use of compaction_control from tool runner calls before upgrading to Python SDK v1.0.",
    },
    {
        "id": "python-sdk-v1-async-with-raw-response",
        "pattern": r"\.with_raw_response\b",
        "applies_if_model": None,
        "severity": "HIGH",
        "deadline": "2026-08-20 (Python SDK v1.0)",
        "title": "Python SDK v1.0 async client: .with_raw_response results require await response.parse()",
        "detail": "On the async client in Python SDK v1.0, results from .with_raw_response now require `await response.parse()`. Existing code accessing the parsed result synchronously will silently misbehave or error.",
        "fix": "Update async .with_raw_response usages to `await response.parse()`.",
    },
    {
        "id": "python-sdk-v1-bedrock-no-default-region",
        "pattern": r"AnthropicBedrock\s*\(",
        "applies_if_model": None,
        "severity": "MEDIUM",
        "deadline": "2026-08-20 (Python SDK v1.0)",
        "title": "Python SDK v1.0 AnthropicBedrock raises an error when no AWS region is configured",
        "detail": "In Python SDK v1.0, AnthropicBedrock no longer silently defaults to us-east-1 when no AWS region is configured; it now raises an error instead.",
        "fix": "Explicitly configure an AWS region (env var or constructor argument) before constructing AnthropicBedrock.",
    },
    {
        "id": "python-sdk-v1-min-python-version",
        "pattern": r"python_requires|Programming Language :: Python :: 3\.[0-9]\b",
        "applies_if_model": None,
        "severity": "MEDIUM",
        "deadline": "2026-08-20 (Python SDK v1.0)",
        "title": "Python SDK v1.0 requires Python 3.10 or later",
        "detail": "Python SDK v1.0 drops support for Python versions below 3.10. This rule only fires on real Python source (e.g. classifiers inside a setup.py setup() call) — it can't see requirements pinned in non-Python files like pyproject.toml.",
        "fix": "Upgrade the project's Python runtime requirement to 3.10+ before installing Python SDK v1.0.",
    },
    {
        "id": "memory-list-managed-agents-header-behavior-change",
        "pattern": r"managed-agents-2026-04-01",
        "applies_if_model": None,
        "severity": "MEDIUM",
        "deadline": "2026-07-22",
        "title": "managed-agents-2026-04-01 header adopts new memory listing behavior",
        "detail": "Since 2026-07-22, the managed-agents-2026-04-01 beta header on memory store list endpoints returns results in stable server-defined order (order_by/order ignored), restricts depth to 0/1/omitted, and requires path_prefix to end with '/'. Old page cursors are invalid.",
        "fix": "Audit memory-list calls using this header: drop reliance on order_by/order, fix depth values, and restart pagination from page one.",
    },
    {
        "id": "computer-use-toolset-new-shape",
        "pattern": r"computer_20251124",
        "applies_if_model": None,
        "severity": "MEDIUM",
        "deadline": "2026-08-19",
        "title": "computer_toolset_20260801 (GA) changes request shape vs. beta computer_20251124",
        "detail": "The computer use tool is now GA as computer_toolset_20260801. Upgrading from the beta computer_20251124 changes the request shape and tool handling (batch actions, zoom enabled by default).",
        "fix": "Follow the migration guide before switching from computer_20251124 to computer_toolset_20260801.",
    },
]

RULES = RULES + NEW_RULES


# --- Auto-extracted by sync_rules.py from release notes through 2026-08-27 ---
RULES_AUTO_20260827 = [
    {
        'id': 'claude-opus-4-1-retired',
        'pattern': r"claude-opus-4-1-20250805",
        'applies_if_model': ['claude-opus-4-1-20250805'],
        'severity': 'HIGH',
        'deadline': '2026-08-05',
        'title': 'Claude Opus 4.1 model retired — all API requests now return an error',
        'detail': 'The model `claude-opus-4-1-20250805` has been retired. Any API request specifying this model ID will now return an error rather than a response. The changelog recommends upgrading to Claude Opus 5.',
        'fix': 'Replace all references to `claude-opus-4-1-20250805` with `claude-opus-5` (or the appropriate versioned Opus 5 model ID) in your API calls.',
    },
    {
        'id': 'computer-use-tool-ga-shape-change',
        'pattern': r"computer_20251124",
        'applies_if_model': None,
        'severity': 'HIGH',
        'deadline': '2026-08-19',
        'title': 'Computer use tool GA (`computer_toolset_20260801`) changes request shape and tool handling vs. beta',
        'detail': 'The computer use tool is now generally available as `computer_toolset_20260801`, which introduces batch actions, zoom enabled by default, and per-member configuration via `configs`. The changelog explicitly warns that upgrading an existing integration changes the request shape and tool handling, and links to a migration guide.',
        'fix': 'Follow the official migration guide at the `#migrate-from-computer-20251124` docs section to update your request payloads and tool-handling code before switching to `computer_toolset_20260801`.',
    },
    {
        'id': 'files-api-beta-header-response-format-change',
        'pattern': r"files-api-2025-04-14",
        'applies_if_model': None,
        'severity': 'MEDIUM',
        'deadline': '2026-08-19',
        'title': 'Files API GA: requests without the beta header now return a different response format',
        'detail': 'The Files API is out of beta; requests to `/v1/files` and Messages API requests referencing uploaded files that omit the `files-api-2025-04-14` beta header now return the new GA response format (including `expires_at`, new pagination fields `page`/`next_page`, and an `ids[]` filter). Code that drops the header but still expects the old response shape will silently misbehave.',
        'fix': 'Keep sending the `files-api-2025-04-14` beta header to preserve the old response format, or update your response-parsing code to handle the new GA format and then remove the header.',
    },
    {
        'id': 'skills-api-beta-header-delete-behavior-change',
        'pattern': r"skills-2025-10-02",
        'applies_if_model': None,
        'severity': 'MEDIUM',
        'deadline': '2026-08-27',
        'title': 'SDK `client.beta.skills` no longer sends beta header; `delete()` now deletes all versions',
        'detail': 'In the listed SDK versions (Python 1.2.0, TypeScript 0.122.0, Go 1.68.0, Java 2.59.0, Ruby 1.67.0, C# 12.44.0), `client.beta.skills` stops sending the `skills-2025-10-02` beta header. As a result, `client.beta.skills.delete()` now deletes a Skill together with all its versions rather than just one, which is a silent and destructive behavior change for code that expected the old scoped-delete semantics.',
        'fix': 'Audit all calls to `client.beta.skills.delete()` and ensure your code accounts for the fact that it will now delete the Skill and every version; migrate to `client.skills` explicitly and update version-management logic accordingly.',
    },
    {
        'id': 'sdk-beta-skill-type-renamed',
        'pattern': r"BetaSkill\b",
        'applies_if_model': None,
        'severity': 'MEDIUM',
        'deadline': '2026-08-27',
        'title': 'Beta Messages type `BetaSkill` renamed to `BetaContainerSkill` in affected SDKs',
        'detail': 'In the same SDK releases (Python 1.2.0, TypeScript 0.122.0, Go 1.68.0, Java 2.59.0, Ruby 1.67.0, C# 12.44.0), the type previously called `BetaSkill` (the container Skill reference in the beta Messages types) is renamed to `BetaContainerSkill`. Code that references the old type name by string or import will break at compile time or runtime.',
        'fix': 'Find all uses of `BetaSkill` in your codebase and rename them to `BetaContainerSkill` when upgrading to the affected SDK versions.',
    },
    {
        'id': 'python-sdk-v1-python-version',
        'pattern': r"python_requires",
        'applies_if_model': None,
        'severity': 'HIGH',
        'deadline': '2026-08-20',
        'title': 'Python SDK v1.0 requires Python 3.10 or later',
        'detail': 'Python SDK v1.0 drops support for Python versions earlier than 3.10. Applications running on Python 3.8 or 3.9 will be unable to install or use the new SDK version.',
        'fix': 'Upgrade your Python runtime to 3.10 or later before updating to Python SDK v1.0.',
    },
    {
        'id': 'python-sdk-v1-text-completions-removed',
        'pattern': r"(?:completions\.create|Completion|text_completion)",
        'applies_if_model': None,
        'severity': 'HIGH',
        'deadline': '2026-08-20',
        'title': 'Python SDK v1.0 removes legacy Text Completions API surface',
        'detail': 'Python SDK v1.0 removes the long-deprecated Text Completions API. Any code that calls the legacy completions endpoint through the SDK will break after upgrading.',
        'fix': 'Migrate all Text Completions API calls to the Messages API before upgrading to Python SDK v1.0.',
    },
    {
        'id': 'python-sdk-v1-messages-params-removed',
        'pattern': r"(?:temperature|top_p|top_k)\s*=",
        'applies_if_model': None,
        'severity': 'HIGH',
        'deadline': '2026-08-20',
        'title': 'Python SDK v1.0 removes `temperature`, `top_p`, and `top_k` parameters on Messages methods',
        'detail': 'Python SDK v1.0 removes the `temperature`, `top_p`, and `top_k` parameters from Messages API method signatures. Code that passes these parameters will raise an error after upgrading.',
        'fix': 'Remove `temperature`, `top_p`, and `top_k` keyword arguments from all Messages API calls in your codebase before upgrading to Python SDK v1.0.',
    },
    {
        'id': 'python-sdk-v1-async-raw-response-parse',
        'pattern': r"\.with_raw_response",
        'applies_if_model': None,
        'severity': 'HIGH',
        'deadline': '2026-08-20',
        'title': 'Python SDK v1.0 async client: `.with_raw_response` results now require `await response.parse()`',
        'detail': 'On the async client in Python SDK v1.0, results returned by `.with_raw_response` must now be awaited with `await response.parse()`. Code that calls `.parse()` without `await` will silently return a coroutine instead of the parsed value.',
        'fix': 'Update all async code that calls `.parse()` on a `.with_raw_response` result to use `await response.parse()`.',
    },
]

RULES = RULES + RULES_AUTO_20260827
