"""
Rule database for OpenAI Python SDK breaking changes — the first step of
turning claude-api-guard from "guards your Anthropic calls" into "guards
your LLM API calls," a much bigger addressable set of real codebases.

Hand-extracted from OpenAI's real, currently-live sources (checked
2026-08-31), same manual-stand-in-for-extract_rules.py approach rules.py
was originally seeded with:

- https://github.com/openai/openai-python/blob/main/httpx2.md — the
  currently-active httpx-to-httpx2 migration guide.
- https://github.com/openai/openai-python/blob/main/CHANGELOG.md — dated
  per version, with an explicit "BREAKING CHANGES" marker per release.
  Structurally better signal than Anthropic's changelog for this one
  purpose: no need to infer breaking-ness from prose, the maintainers
  already flag it.
- https://github.com/openai/openai-python/discussions/742 — the v0.x to
  v1.0.0 migration guide (2023). Older, but the same *kind* of risk
  rules.py already tracks for Anthropic (its own "legacy Text Completions
  API removed" rule): code copy-pasted from an old tutorial or an
  unmaintained internal script that still uses pre-v1 call shapes.

Notable validating detail for the whole "expand to multiple providers"
idea: the httpx-to-httpx2 migration hitting OpenAI's SDK is the *same*
underlying industry event as the one already tracked for Anthropic in
rules.py (python-sdk-v1-httpx-to-httpx2) — httpx itself going
unmaintained, httpx2 forked by Pydantic Services Inc. Both SDKs are
generated by the same tool (Stainless), so this kind of shared,
cross-provider breaking change is likely to recur — real evidence this
isn't a one-off coincidence, it's a structural reason multi-provider
coverage is worth building.

Every rule here needs "provider": "openai" — ast_scan.py's per-file
import precondition (file_references_openai) uses it to gate the
httpx-style rule, exactly the same way file_references_anthropic already
gates the Anthropic one. A rule with no "provider" key defaults to
"anthropic" for backward compatibility with rules.py's existing entries,
which predate this field and were never given one.
"""

RULES_OPENAI = [
    {
        "id": "openai-httpx-to-httpx2",
        "provider": "openai",
        "pattern": r"import\s+httpx(?!2)|from\s+httpx(?!2)\s+import|httpx\.(Client|AsyncClient|Timeout|MockTransport)",
        "applies_if_model": None,
        "severity": "HIGH",
        "deadline": "already active",
        "title": "OpenAI Python SDK moves HTTP layer from httpx to httpx2",
        "detail": (
            "The SDK's http_client support has moved from httpx to httpx2 "
            "(httpx itself has had no releases since 2024 and is "
            "effectively unmaintained; httpx2 is its maintained successor, "
            "built by Pydantic Services Inc. with the original httpx "
            "author). A custom http_client=httpx.Client(...) passed to "
            "OpenAI()/AsyncOpenAI(), or any httpx.Timeout/MockTransport "
            "object, needs an httpx2 equivalent. httpx2 also verifies TLS "
            "certificates against the OS trust store instead of the "
            "certifi bundle the SDK used to install — this specifically "
            "breaks minimal container images and corporate proxies that "
            "relied on a custom certifi bundle."
        ),
        "fix": (
            "Replace httpx.Client()/httpx.Timeout()/httpx.MockTransport() "
            "with the httpx2 equivalents (openai.DefaultHttpx2Client and "
            "friends). If a custom CA bundle was relied on via certifi, "
            "set SSL_CERT_FILE or pass an explicit ssl.SSLContext instead."
        ),
    },
    {
        "id": "openai-v2-tool-call-output-type-widened",
        "provider": "openai",
        # Deliberately narrow to the two named types themselves, not a
        # generic ".output[0]" shape. Real bug, found testing this
        # against litellm (not guessed): an earlier version of this
        # pattern also matched bare `.output[0]` to catch code indexing
        # into the field directly — but ".output" indexed at [0] is an
        # extremely common, totally generic naming convention (any
        # response wrapper, any test fixture), and it drowned the two
        # real hits in litellm in ~15 unrelated ones. Better to
        # under-report (miss code that reads .output without ever
        # naming these types) than keep that noise.
        "pattern": r"ResponseFunctionToolCallOutputItem|ResponseCustomToolCallOutput",
        "applies_if_model": None,
        "severity": "MEDIUM",
        "deadline": "2025-09-30 (Python SDK v2.0.0)",
        "title": "SDK v2.0.0 widens tool-call output's type from string to string | array",
        "detail": (
            "ResponseFunctionToolCallOutputItem.output and "
            "ResponseCustomToolCallOutput.output changed from always being "
            "a plain string to `string | Array<ResponseInputText | "
            "ResponseInputImage | ResponseInputFile>`. Code that assumes "
            "`.output` is always a string (e.g. passing it straight into a "
            "string-only function, or indexing into it like a string) can "
            "break or misbehave silently once a caller starts sending back "
            "structured content."
        ),
        "fix": "Check the type of `.output` at runtime (str vs. list) before treating it as plain text.",
    },
    {
        "id": "openai-v1-legacy-module-level-calls-removed",
        "provider": "openai",
        "pattern": r"openai\.(ChatCompletion|Completion|Embedding|Image|FineTune|File)\.(create|acreate|download)|openai\.api_key\s*=|openai\.api_base\s*=",
        "applies_if_model": None,
        "severity": "HIGH",
        "deadline": "already active (Python SDK v1.0.0, 2023)",
        "title": "Pre-v1.0 module-level call style removed (openai.ChatCompletion.create, openai.api_key = ..., etc.)",
        "detail": (
            "SDK v1.0.0 replaced the old module-level style — setting "
            "openai.api_key directly and calling openai.ChatCompletion."
            "create(...)/openai.Completion.create(...)/openai.Embedding."
            "create(...)/openai.Image.create(...)/openai.FineTune.create(...) "
            "— with an explicit client object (client = OpenAI(...); "
            "client.chat.completions.create(...)). Old, still-active code "
            "isn't rare: this is exactly the kind of thing that survives in "
            "a copy-pasted tutorial snippet or an unmaintained internal "
            "script, the same risk rules.py already tracks for Anthropic's "
            "own legacy Text Completions removal."
        ),
        "fix": (
            "Instantiate a client (client = OpenAI(api_key=...)) and call "
            "methods on it: client.chat.completions.create(...), "
            "client.embeddings.create(...), client.images.generate(...), "
            "client.fine_tuning.jobs.create(...)."
        ),
    },
    {
        "id": "openai-v1-error-classes-renamed",
        "provider": "openai",
        "pattern": r"openai\.InvalidRequestError|except\s+openai\.OpenAIError\b",
        "applies_if_model": None,
        "severity": "MEDIUM",
        "deadline": "already active (Python SDK v1.0.0, 2023)",
        "title": "Pre-v1.0 error class names removed (InvalidRequestError, bare OpenAIError catch-all)",
        "detail": (
            "openai.InvalidRequestError was renamed to openai.BadRequestError "
            "in SDK v1.0.0. Code that still imports or catches the old name "
            "will raise AttributeError/NameError instead of catching the "
            "real error, or a broad `except openai.OpenAIError` written for "
            "the old exception hierarchy may no longer catch what it used "
            "to."
        ),
        "fix": "Catch openai.BadRequestError instead of openai.InvalidRequestError; review broad OpenAIError handlers against the current exception hierarchy.",
    },
]
