"""
Rule database for Claude/Anthropic API breaking changes.

This version was partly regenerated by actually reading Anthropic's live
release notes (fetched 2026-08-27) and extracting structured rules from the
raw changelog text — this is a manual stand-in for the step that should run
automatically via an LLM call in the real product (see extract_rules.py).

One correction from the first version: "sampling-params-rejected" was
originally attributed to specific *models* (Opus 4.7+/Sonnet 5). The actual
changelog entry (Python SDK v1.0, 2026-08-20) shows it's an *SDK-version*
change — v1.0 removes temperature/top_p/top_k from Messages methods
entirely, for any model. That's a meaningfully different (and more useful)
condition to check for. Left as a lesson: a hand-written rule can be subtly
wrong even when it "sounds right" — this is exactly why the real rule
database needs to come from the source text, not paraphrase.
"""

RULES = [
    {
        "id": "sdk-v1-sampling-params-removed",
        "pattern": r"(?<!#)\b(temperature|top_p|top_k)\s*=\s*[0-9.]+",
        "applies_if_model": None,  # SDK-version issue, not model-specific
        "severity": "HIGH",
        "deadline": "2026-08-20 (Python SDK v1.0)",
        "title": "temperature/top_p/top_k removed from Messages methods in Python SDK v1.0",
        "detail": (
            "Python SDK v1.0 (2026-08-20) removes temperature, top_p, and "
            "top_k from Messages methods entirely — for any model, not a "
            "specific one. Correction from an earlier version of this rule, "
            "which wrongly scoped it to Opus 4.7+/Sonnet 5 only."
        ),
        "fix": "Remove the parameter, or pin anthropic<1.0 until you've migrated (see the v1 migration guide).",
    },
    {
        "id": "sdk-v1-text-completions-removed",
        "pattern": r"client\.completions\.create|anthropic\.Completion",
        "applies_if_model": None,
        "severity": "HIGH",
        "deadline": "2026-08-20 (Python SDK v1.0)",
        "title": "Legacy Text Completions API removed in Python SDK v1.0",
        "detail": "The old Text Completions surface is gone in v1.0 of the Python SDK.",
        "fix": "Migrate to the Messages API (client.messages.create).",
    },
    {
        "id": "manual-thinking-budget",
        "pattern": r"thinking\s*=\s*\{\s*[\"']type[\"']\s*:\s*[\"']enabled[\"']\s*,\s*[\"']budget_tokens[\"']",
        "applies_if_model": ["opus-4-7", "opus-5", "sonnet-5"],
        "severity": "HIGH",
        "deadline": "already active",
        "title": "Manual thinking budget rejected — needs adaptive thinking",
        "detail": (
            "Manually specifying a fixed thinking token budget is being "
            "phased out in favor of adaptive thinking / effort levels."
        ),
        "fix": "Replace budget_tokens with an `effort` level (e.g. \"high\", \"xhigh\").",
    },
    {
        "id": "opus5-effort-xhigh-thinking-disabled",
        "pattern": r"effort\s*=\s*[\"'](xhigh|max)[\"']",
        "applies_if_model": ["opus-5"],
        "severity": "MEDIUM",
        "deadline": "2026-07-24 (Claude Opus 5 launch)",
        "title": "Disabling thinking at xhigh/max effort is rejected on Opus 5",
        "detail": (
            "Confirmed directly in the Opus 5 release notes (2026-07-24): "
            "thinking: {\"type\": \"disabled\"} with effort xhigh/max returns "
            "a 400 error. This is a documented behavior change from Opus 4.8."
        ),
        "fix": "Either drop the explicit thinking=disabled, or lower the effort level.",
    },
    {
        "id": "assistant-prefill-removed",
        "pattern": r"[\"']role[\"']\s*:\s*[\"']assistant[\"']\s*,\s*[\"']content[\"']\s*:\s*[\"'][^\"']*[\"']",
        "applies_if_model": ["opus-4-7", "opus-5", "sonnet-5"],
        "severity": "MEDIUM",
        "deadline": "already active",
        "title": "Assistant message prefill removed on recent models",
        "detail": "Pre-filling the start of the assistant's reply is no longer supported on newer models.",
        "fix": "Move the prefilled text into the system prompt or a formatting instruction instead.",
    },
    {
        "id": "experimental-endpoint-retiring",
        "pattern": r"/v1/experimental/(generate_prompt|improve_prompt|templatize_prompt)",
        "applies_if_model": None,
        "severity": "HIGH",
        "deadline": "2026-08-17 (already passed)",
        "title": "Experimental prompt endpoints retired",
        "detail": "generate_prompt / improve_prompt / templatize_prompt under /v1/experimental/ have been shut down.",
        "fix": "Migrate to the stable prompt-engineering workflow in the Console, or vendor the logic yourself.",
    },
    {
        "id": "model-deprecated-sonnet4-opus4",
        "pattern": r"claude-(sonnet|opus)-4-\d{8}",
        "applies_if_model": None,
        "severity": "HIGH",
        "deadline": "deprecated — migrate now",
        "title": "Pinned to a deprecated Claude 4 model snapshot",
        "detail": "Claude Sonnet 4 and Opus 4 are deprecated in favor of the 4.5/5 line.",
        "fix": "Update the model string to the current Sonnet/Opus 5 snapshot.",
    },
    {
        "id": "model-retired-opus-4-1",
        "pattern": r"claude-opus-4-1-20250805",
        "applies_if_model": None,
        "severity": "HIGH",
        "deadline": "2026-08-05 (already retired)",
        "title": "Claude Opus 4.1 fully retired — all requests now error",
        "detail": "Confirmed in the 2026-08-05 release notes: Opus 4.1 (claude-opus-4-1-20250805) is fully retired. Every request to it now returns an error, not a warning.",
        "fix": "Upgrade to Claude Opus 5.",
    },
    {
        "id": "fast-mode-removed-opus-4-7",
        "pattern": r"claude-opus-4-7[\s\S]{0,200}speed\s*[:=]\s*[\"']fast[\"']",
        "applies_if_model": None,
        "severity": "MEDIUM",
        "deadline": "2026-07-24 (Claude Opus 5 launch)",
        "title": "Fast mode removed for Claude Opus 4.7 — now errors instead of falling back",
        "detail": (
            "Requests to claude-opus-4-7 with speed: \"fast\" now return an "
            "error. Unlike Opus 4.6, they no longer silently fall back to "
            "standard speed."
        ),
        "fix": "Migrate to Claude Opus 5 or Opus 4.8 to keep using fast mode.",
    },
    {
        "id": "model-tentative-retirement-sonnet45",
        "pattern": r"claude-sonnet-4-5",
        "applies_if_model": None,
        "severity": "LOW",
        "deadline": "no retirement currently scheduled (confirmed 2026-08-27)",
        "title": "Claude Sonnet 4.5 — status check",
        "detail": "Verified directly against Anthropic's release notes: Sonnet 4.5 has no deprecation scheduled as of 2026-08-27. Downgraded from an earlier, unverified MEDIUM-severity guess.",
        "fix": "No action needed right now — just keep an eye on the release notes.",
    },
]
